import './styles.css';
import './main';
import './globalTable';
import './map';
import './dataStructuring';
import './dataSort';
import './countriesTable';
import './eventListener';
import './search';
